name: 'Set the next commit schedule'

on:
  schedule:
    - cron: '12 10 * * *'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  next-cron:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 'Checkout GitHub repository'
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.WORKFLOW_TOKEN }}'

      - name: 'Determine next cron schedule'
        run: ./next-cron.sh

      - name: 'Configure Git identity'
        run: |
          git config --global user.name 'Alejandro de Haro'
          git config --global user.email 'adeharo9@users.noreply.github.com'

      - name: 'Commit changes'
        run: |
          git add .github/workflows/next-cron.yml
          git commit -m "Automated cron change: next run at $(cat next-cron.txt) UTC"

      - name: 'Push changes to GitHub repository'
        run: git push
